apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-certmgr
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lestermiller26@gmail.com
    privateKeySecretRef:
      name: letsencrypt-certmgr
    solvers:
      - http01:
          ingress:
            class: nginx