# Velero Credentials Secret for DigitalOcean Spaces
# Note: Replace the credentials with actual values before applying
apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id=YOUR_DO_SPACES_ACCESS_KEY
    aws_secret_access_key=YOUR_DO_SPACES_SECRET_KEY